# Generated by Django 4.1.1 on 2023-01-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_userprofile_id_userprofile_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sno',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
